project 'ios.xcodeproj'
platform :ios, '9.0'

target 'ios' do
use_frameworks!

pod 'SDWebImage', '~> 4.1.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'OMGHTTPURLRQ', '~> 3.2.2'
pod 'Groot/ObjC', '~> 3.0-beta.1'
pod 'ILGHttpConstants', '~> 2.0.0'

end
